# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FWall.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QAction, QLineEdit, QMessageBox, QPushButton
import Galerkin_GUI

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_simulation = QtWidgets.QAction(MainWindow)
        self.actionNew_simulation.setObjectName("actionNew_simulation")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setMenuRole(QtWidgets.QAction.NoRole)
        self.actionExit.setObjectName("actionExit")
        self.actionMaximize = QtWidgets.QAction(MainWindow)
        self.actionMaximize.setObjectName("actionMaximize")
        self.actionUnmaximize = QtWidgets.QAction(MainWindow)
        self.actionUnmaximize.setObjectName("actionUnmaximize")
        self.actionMinimize = QtWidgets.QAction(MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.menuFile.addAction(self.actionNew_simulation)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionMaximize)
        self.menuView.addAction(self.actionUnmaximize)
        self.menuView.addAction(self.actionMinimize)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.simulationWindow = start_simulation()

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        self.actionMaximize.triggered.connect(MainWindow.showMaximized)
        self.actionUnmaximize.triggered.connect(MainWindow.showNormal)
        self.actionMinimize.triggered.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.actionNew_simulation.triggered.connect(self.new_sim_clicked)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FWall"))
        self.menuFile.setTitle(_translate("MainWindow", "FWall"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionNew_simulation.setText(_translate("MainWindow", "New simulation"))
        self.actionNew_simulation.setStatusTip(_translate("MainWindow", "Create a new simulation"))
        self.actionNew_simulation.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Save simulation"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save current simulation"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit program"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionMaximize.setText(_translate("MainWindow", "Maximize"))
        self.actionMaximize.setStatusTip(_translate("MainWindow", "Maximize window"))
        self.actionMaximize.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionUnmaximize.setText(_translate("MainWindow", "Unmaximize"))
        self.actionUnmaximize.setStatusTip(_translate("MainWindow", "Unmaximize window"))
        self.actionUnmaximize.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))
        self.actionMinimize.setStatusTip(_translate("MainWindow", "Minimize window"))
        self.actionMinimize.setShortcut(_translate("MainWindow", "Ctrl+K"))

    def new_sim_clicked(self):
        self.simulationWindow.show()

class start_simulation(QtWidgets.QMainWindow):
    def __init__(self):
        super(start_simulation,self).__init__()
        self.resize(720, 540)
        self.setWindowTitle("Simulation Window")
        
        self.label_1 = QtWidgets.QLabel(self)
        self.label_2 = QtWidgets.QLabel(self)
        self.label_3 = QtWidgets.QLabel(self)
        self.label_4 = QtWidgets.QLabel(self)
        self.label_5 = QtWidgets.QLabel(self)
        self.label_6 = QtWidgets.QLabel(self)
        self.label_7 = QtWidgets.QLabel(self)
        self.label_8 = QtWidgets.QLabel(self)
        self.label_9 = QtWidgets.QLabel(self)
        self.label_10 = QtWidgets.QLabel(self)
        self.label_11 = QtWidgets.QLabel(self)
        self.label_12 = QtWidgets.QLabel(self)
        self.runButton = QPushButton("Run",self)


        self.runButton.move(435,400)
        self.runButton.resize(200,100)
        

        self.label_1.setText("Parameters")
        self.label_1.move(300,30)
        self.label_1.setFont(QtGui.QFont("times",18))
        self.label_1.adjustSize()

        self.label_2.setText("Number of wings:")
        self.label_2.move(50,105)
        self.label_2.setFont(QtGui.QFont("Arial",12))
        self.label_2.adjustSize()

        self.textbox2 = QLineEdit(self)
        self.textbox2.move(200,100)
       
        
        self.label_3.setText("Wing span [m]:")
        self.label_3.move(50,155)
        self.label_3.setFont(QtGui.QFont("Arial",12))
        self.label_3.adjustSize()

        self.textbox3 = QLineEdit(self)
        self.textbox3.move(200,150)
        

        self.label_4.setText("AoA [°]:")
        self.label_4.move(50,210)
        self.label_4.setFont(QtGui.QFont("Arial",12))
        self.label_4.adjustSize()

        self.textbox4 = QLineEdit(self)
        self.textbox4.move(200,205)
        

        self.label_5.setText("y-offset [m]:")
        self.label_5.move(50,270)
        self.label_5.setFont(QtGui.QFont("Arial",12))
        self.label_5.adjustSize()

        self.textbox5 = QLineEdit(self)
        self.textbox5.move(200,265)
        

        self.label_6.setText("z-offset [m]:")
        self.label_6.move(50,325)
        self.label_6.setFont(QtGui.QFont("Arial",12))
        self.label_6.adjustSize()

        self.textbox6 = QLineEdit(self)
        self.textbox6.move(200,320)
        

        self.label_7.setText("Element type:")
        self.label_7.move(50,375)
        self.label_7.setFont(QtGui.QFont("Arial",12))
        self.label_7.adjustSize()

        self.textbox7 = QLineEdit(self)
        self.textbox7.move(200,370)
        
        
        self.label_8.setText("Mesh type:")
        self.label_8.move(50,430)
        self.label_8.setFont(QtGui.QFont("Arial",12))
        self.label_8.adjustSize()

        self.textbox8 = QLineEdit(self)
        self.textbox8.move(200,430)
        
        
        self.label_9.setText("Want to plot figures together?\n(S/N)")
        self.label_9.move(50,485)
        self.label_9.setFont(QtGui.QFont("Arial",12))
        self.label_9.adjustSize()

        self.textbox9 = QLineEdit(self)
        self.textbox9.move(280,485)
        self.textbox9.resize(30,30)
        

        self.label_10.setText("Wing type\n(Planar or Flexibe):")
        self.label_10.move(380,90)
        self.label_10.setFont(QtGui.QFont("Arial",12))
        self.label_10.adjustSize()

        self.textbox10 = QLineEdit(self)
        self.textbox10.move(535,100)
        

        self.label_11.setText("Number of elements:")
        self.label_11.move(370,155)
        self.label_11.setFont(QtGui.QFont("Arial",12))
        self.label_11.adjustSize()

        self.textbox11 = QLineEdit(self)
        self.textbox11.move(535,150)
        

        self.label_12.setText("r:")
        self.label_12.move(505,210)
        self.label_12.setFont(QtGui.QFont("Arial",12))
        self.label_12.adjustSize()

        self.textbox12 = QLineEdit(self)
        self.textbox12.move(535,205)
        
        self.runButton.clicked.connect(self.on_click)
        self.runButton.clicked.connect(self.call_Galerkin_def)

    def on_click(self):

        self.Nwings = int(self.textbox2.text())
        self.span = float(self.textbox3.text())
        self.AoA_user = float(self.textbox4.text())
        self.y_offset_user = float(self.textbox5.text())
        self.z_offset_user = float(self.textbox6.text())
        self.elem_type= self.textbox7.text()
        self.mesh_type = self.textbox8.text()
        self.plot_together= self.textbox9.text()
        self.wing_type = self.textbox10.text()
        self.Nelem = int(self.textbox11.text())
        self.r = float(self.textbox12.text())
        return #self.Nwings, span, AoA_user, y_offset_user, z_offset_user, elem_type, mesh_type, plot_together, wing_type, Nelem, r
    
    def call_Galerkin_def(self):
        Galerkin_GUI.call_Galerkin(self.Nwings, self.span, self.AoA_user, self.y_offset_user,
         self.z_offset_user, self.elem_type, self.mesh_type, self.plot_together, self.wing_type, self.Nelem, self.r)    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sim = start_simulation()
    sys.exit(app.exec_())



